### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by Irostovsky** [drc-ima/test-task#1]
Hi @drc-ima 
I m Ivan, from GuestReady.
Thanks for the doing the task.
I have couple notes regarding the code:
1. Why the [adding of rental](https://github.com/drc-ima/test-task/blob/main/rental/views.py#L12) is a FBV but the [adding of the reservation](https://github.com/drc-ima/test-task/blob/main/rental/views.py#L36) is a CBV?
2. Regarding the [previous reservation](https://github.com/drc-ima/test-task/blob/main/rental/templatetags/rentaltags.py#L23):
  - for now you get the previous by the reservation ID, but it reality the reservation with future dates could be added earlier then reservation with older dates, ie Res-1: 1-10 June created today and Res-2: 23-25 May would be created tomorrow. 
  - the way is not efficient as code does extra SQL requests. Could you please optimize it?

Let me know if some questions.

**Comment by drc-ima** [comment]
Thanks for your response Ivan,

1. I used CBV for adding reservations because it makes it easier to implement django forms with it. Although FBV could have served the same purpose

2. Thanks for your feedback on this. I will rewrite the query to achieve optimization.

**Comment by drc-ima** [comment]
Hi Ivan, kindly review the codes [here](https://github.com/drc-ima/test-task/blob/7f10ed3c4f77b77e9bfb10866c168b40d8e08898/rental/views.py#L35-L38).

**Comment by drc-ima** [comment]
@Irostovsky

**Comment by Irostovsky** [comment]
Hi @drc-ima 
I m in vacation this week. I will review on 23/May.

**Comment by Irostovsky** [comment]
Hi @drc-ima 
I like your idea with subquery https://github.com/drc-ima/test-task/blob/main/rental/views.py#L35
But in the real life the reservations could be created not sequentially, ie res-1: June 20-25 and then res-2 May 30-31. So the code for now show the previous a little bit wrong. Please fix.
Thanks!

**Comment by drc-ima** [comment]
Hi @Irostovsky 

Thanks for your feedback. I have updated the views file as: [https://github.com/drc-ima/test-task/blob/d1e1a579d21a2e18917a8bbfb1c5f9de9375ec4d/rental/views.py#L39-L40](https://github.com/drc-ima/test-task/blob/d1e1a579d21a2e18917a8bbfb1c5f9de9375ec4d/rental/views.py#L39-L40) to suggest the use of the checkin date to get the previous reservation. Hope this is a fix? Thanks

**Comment by drc-ima** [comment]
Also I get from your feedback you would have used a different approach to the subquery approach. PleaseI would be glad if you could share that too. Thanks

**Comment by Irostovsky** [comment]
Hi @drc-ima 
Thanks for the change. Now it makes sense for me.
I m not sure I understand your question about subquery. You already use it.

**Comment by drc-ima** [comment]
Thanks @Irostovsky. 

Hope this is enough to close this issue. 

And also please what are the next steps?

**Comment by Irostovsky** [comment]
@drc-ima will ping you about the screen call date. See you.
